### ISSUE TITLE
AlexNet ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by TheDoorIsBroken** [deeplearning4j/ImageNet-Example#12]
I create and initialise an object of AlexNet, feed data in and get a series of ArrayIndexOutOfBoundsException when runiing model.fit

Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.blockUntilComplete(CPUIm2ColTask.java:715)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.invokeBlocking(CPUIm2ColTask.java:702)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.invokeBlocking(CPUIm2ColTask.java:19)
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:137)
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:100)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:135)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:356)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:513)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:636)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:590)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1752)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:132)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1497)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1529)
	at org.deeplearning4j.examples.convolution.miniatureBaseDetectorAlexNet.main(miniatureBaseDetectorAlexNet.java:217)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.blockUntilComplete(CPUIm2ColTask.java:713)
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	... 18 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.reportResult(Unknown Source)
	at java.util.concurrent.ForkJoinTask.join(Unknown Source)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.splitOrExecute(CPUIm2ColTask.java:203)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.compute(CPUIm2ColTask.java:100)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.compute(CPUIm2ColTask.java:19)
	at java.util.concurrent.RecursiveTask.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.execTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.util.concurrent.ForkJoinPool.work(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.reportResult(Unknown Source)
	at java.util.concurrent.ForkJoinTask.join(Unknown Source)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.splitOrExecute(CPUIm2ColTask.java:203)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.compute(CPUIm2ColTask.java:100)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.compute(CPUIm2ColTask.java:19)
	at java.util.concurrent.RecursiveTask.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.helpJoinTask(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.joinTask(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doJoin(Unknown Source)
	... 10 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 12288
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.doHeapFloat(CPUIm2ColTask.java:302)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.execute(CPUIm2ColTask.java:220)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.splitOrExecute(CPUIm2ColTask.java:207)
	... 17 more

**Comment by nyghtowl** [comment]
Changes to Canova constructor required updates to how the data is loaded. This is fixed.
