### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path error

### ISSUE THREAD

**Issue by deepali-c** [deeplearning4j/ImageNet-Example#22]
I am using a PPC 64 machine to execute the ImageNet-Example for Alexnet:

I have updated the pom.xml to use 0.5.0 versions for nd4j, dl4j and datavec.

While executing AlexNet sample I see the following error:
java -cp target/Imagenet-Example-0.4-rc0-SNAPSHOT.jar imagenet.ImageNetMain --version Standard --modelType AlexNet
[main] INFO org.reflections.Reflections - Reflections took 548 ms to scan 1 urls, producing 111 keys and 368 values
Build model....
[main] INFO imagenet.ImageNetStandardExample - Training with no transform
Load data....
Train model....
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1889)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726)
        at org.bytedeco.javacpp.Loader.load(Loader.java:501)
        at org.bytedeco.javacpp.Loader.load(Loader.java:418)
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:278)
        at org.bytedeco.javacpp.Loader.load(Loader.java:473)
        at org.bytedeco.javacpp.Loader.load(Loader.java:418)
        at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13)
        at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:193)
        at imagenet.Utils.ImageNetRecordReader.next(ImageNetRecordReader.java:75)
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:171)
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:347)
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:46)
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.run(AsyncDataSetIterator.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp1176234266740952/libjniopencv_core.so: /tmp/javacpp1176234266740952/libopencv_core.so.3.1: symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1968)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1893)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:709)
        ... 15 more
Exception in thread "main" java.lang.IllegalStateException: Unexpected state occurred for AsyncDataSetIterator: runnable died or no data available
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:226)
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:35)
        at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:99)
        at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:122)
        at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:36)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1048)
        at imagenet.ImageNetStandardExample.trainModel(ImageNetStandardExample.java:81)
        at imagenet.ImageNetStandardExample.initialize(ImageNetStandardExample.java:49)
        at imagenet.ImageNetMain.run(ImageNetMain.java:125)
        at imagenet.ImageNetMain.main(ImageNetMain.java:195)

The symbol listing shown for the below command, does not contain the required symbol.
readelf --wide --symbols /usr/lib/gcc/powerpc64le-linux-gnu/4.9/libstdc++.so | grep "3.4.21"

How can I resolve this issue?

Regards
Deepali

**Comment by nyghtowl** [comment]
Did you install javacpp and DataVec repos?

**Comment by nyghtowl** [comment]
Closing this since code base and repo changes. Please reopen if you are still seeing this.
